version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: queueshield-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: queueshield
      POSTGRES_PASSWORD: queueshield_secret
      POSTGRES_DB: queueshield
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: queueshield-redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes

volumes:
  pgdata:
  redisdata:
